apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  labels:
    app: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: nginx
        image: docker.redpanda.com/redpandadata/console:latest
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BROKERS
          value: my-cluster-kafka-brokers.kafka-tests.svc.cluster.local:9092
        - name: KAFKA_SASL_ENABLED
          value: "true"
        - name: KAFKA_SASL_USERNAME
          value: kowl
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kowl
              key: password
        - name: KAFKA_SASL_MECHANISM
          value: SCRAM-SHA-512
        - name: KAFKA_TLS_ENABLED
          value: "true"
        - name: KAFKA_TLS_INSECURESKIPTLSVERIFY
          value: "true"
        - name: KAFKA_TSL_CAFILEPATH
          value: /var/run/secrets/custom/ca.crt
        volumeMounts:
        - name: my-cluster-ca
          mountPath: /var/run/secrets/custom
          readOnly: true
      volumes:
      - name: my-cluster-ca
        secret:
          secretName: my-cluster-cluster-ca-cert
          items:
          - key: ca.crt
            path: ca.crt
---
kind: Service
apiVersion: v1
metadata:
  name: kowl-service
  namespace: kafka-tests
spec:
  ports:
    - name: kowl-port
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  selector:
    app: redpanda-console
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kowl
  namespace: kafka-tests
spec:
  to:
    kind: Service
    name: kowl-service
    weight: 100
  port:
    targetPort: kowl-port
  tls:
    termination: edge
  wildcardPolicy: None
