apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kowl
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - host: '*'
      operations:
        - All
      resource:
        name: my-topic
        patternType: literal
        type: topic
    - host: '*'
      operations:
        - All
      resource:
        type: cluster
      type: allow